name: "Testing Branch Action"

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: |
          docker build -t webui:test .
